### ISSUE TITLE
To generate a model by using various distributions

### ISSUE THREAD

**Issue by zeeshan5885** [Qazalbash/jaxampler#72]
### Description

If we have $X_1,X_2,X_3,\cdots,X_n$, then we should be able to combine them to generate a new model based on them. such as $Y = f(X_1,X_2,X_3,\cdots,X_n)$, where $f$ is any computable function. The generated random number would be IIDs.

**Comment by Qazalbash** [comment]
@zeeshan5885 this is a good idea :v:. Any mechanism that could compute the expressions of type `GenericRV` would make it more flexible ✊🏼 and powerful 💪🏼. Thanks for the report ❤️!

**Comment by Qazalbash** [comment]
I see the solution to this issue in the following parts.

1. A mechanism that can recognize multiple objects of `GenericRV` that are manipulated by a computational function.
2. After the objects have been stored and the pattern has been recognized then we would have to calculate the xxfs and apply the same expression.

We can achieve this goal using Expression Trees. They are standard practice in the evaluation of expression in computer science. One potential problem that can arise in the following situation, let's suppose we have two random variables, $X:\Omega\rightarrow\mathbb{R}$ and $Y$, where $Y:\Omega^2\rightarrow\mathbb{R}$, and we combine them using addition to form $Z$.
$$Z:=X+Y\implies f_{Z}(\omega_1,\omega_2)=f_{X}(\omega_1)+f_{Y}(\omega_1,\omega_2)$$
In this case, we have to pass arguments carefully. At the moment I have only one idea to handle this situation which is to use key word arguments instead of position arguments.

**Comment by Qazalbash** [comment]
We can also notice that only the PDFs of the random variable combine the same way as the function combines the random variable. This is not always true for other XXFs.
